### ISSUE TITLE
Type2Scd.upsert should take a Delta Table argument, not a path

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#24]
`Type2Scd.upsert` should take a Delta Table argument so it's more flexible.  At the moment it only takes a path, so it only works for path based tables.  This method will also work for Hive table names if the user can pass a table name as the argument.

**Comment by ilyasse05** [comment]
I think it would be more easy, to let upsert with 2 arguments path ou deltaTable, and add another level, UpsertPath(path) -> call upsert
UpsertDelta(deltatable) -> call upsert
It's will simplify update or fix bug on update, also add future param if necessary and also simply to use for devloper.

**Comment by brayanjuls** [comment]
I agreed that a Delta table as an input parameter is better because it will enforce using delta and we won't need to apply validation or throw exceptions inside the function because of its misuse. 

If people want to use this in hive tables we could implement it in the diana project as well. 

I will take this issue.
